In [2]:
%run "E:\Users\puzheng\Documents\Startup_py3.py"
sys.path.append(r"E:\Users\puzheng\Documents")

import ImageAnalysis3 as ia
%matplotlib notebook

from ImageAnalysis3 import *
print(os.getpid())

Exception: File `'E:\\Users\\puzheng\\Documents\\Startup_py3.py'` not found.

# calculate rotation and transposition matrix

In [2]:
data_folder = r'\\storm6-pc\STORM6-FLASHDrive\Pu\20201127-NOAcr_CTP-08_E14_brain_no_clearing'
before_position_file = os.path.join(data_folder, '10x_positions.txt')
after_position_file = os.path.join(data_folder, '10x_positions_after.txt')


In [3]:
R, T = alignment_tools.align_manual_points(before_position_file, after_position_file, save=False)


- Manually picked points aligned, rotation:
[[ 0.99989683 -0.01436443]
 [ 0.01436443  0.99989683]],
 translation:[ 593.98776915 -207.2862716 ]


# transpose 60x positions

In [4]:
old_positions = np.loadtxt(os.path.join(data_folder, 'positions_all.txt'), delimiter=',')

In [5]:
new_positions = np.dot(old_positions, R) + T
print(new_positions)

[[-3331.05751255 -4073.80416197]
 [-3328.19755482 -3874.72470385]
 [-3325.33759709 -3675.64524574]
 [-3322.4790758  -3476.66577732]
 [-3319.61911806 -3277.5863192 ]
 [-3316.75916033 -3078.50686109]
 [-3117.7796919  -3081.36538238]
 [-3120.63964963 -3280.4448405 ]
 [-3123.49960737 -3479.52429861]
 [-3126.35812866 -3678.50376703]
 [-3129.21808639 -3877.58322515]
 [-3132.07804413 -4076.66268326]
 [-2932.99858602 -4079.52264099]
 [-2930.13862828 -3880.44318288]
 [-2927.27867055 -3681.36372477]
 [-2924.42014926 -3482.38425634]
 [-2921.56019152 -3283.30479823]
 [-2918.70023379 -3084.22534012]
 [-2719.62077568 -3087.08529785]
 [-2722.48073341 -3286.16475596]
 [-2725.34069115 -3485.24421407]
 [-2728.19921244 -3684.2236825 ]
 [-2731.05917017 -3883.30314061]
 [-2733.9191279  -4082.38259872]
 [-2534.93965948 -4085.24112001]
 [-2532.07970174 -3886.1616619 ]
 [-2529.21974401 -3687.08220379]
 [-2526.36122272 -3488.10273536]
 [-2523.50126498 -3289.02327725]
 [-2520.64130725 -3089.94381914]
 [-2321.56

In [6]:
save_filename = os.path.join(data_folder, 'translated_positions_all.txt')
print(save_filename)
np.savetxt(save_filename, new_positions, fmt='%.2f', delimiter=',')

\\storm6-pc\STORM6-FLASHDrive\Pu\20201127-NOAcr_CTP-08_E14_brain_no_clearing\translated_positions_all.txt


# further adjust manually

In [4]:
import numpy as np

In [18]:
man_old_positions = np.array([[-7888.1,  -3340.4],[-6498.9, 14.0],[-5250.8, 421.4]])

man_adjusted_positions = np.array([[-7893.5, -3342.5],[-6505.4, 12.5],[-5256.5, 418.1]])

manual_shift = man_adjusted_positions- man_old_positions
print(manual_shift)


manual_shift_ave = np.mean(manual_shift,axis=0)
manual_shift_ave

[[-5.4 -2.1]
 [-6.5 -1.5]
 [-5.7 -3.3]]


array([-5.86666667, -2.3       ])

In [19]:
data_folder = r'D:\Shiwei\20210706-P_Forebrain_CTP09_only'

In [20]:
new_positions = np.loadtxt(os.path.join(data_folder, 'positions_all.txt'), delimiter=',')

In [21]:
#manual_shift = np.array([-28.1,  -8.7])
adjusted_new_positions = new_positions + manual_shift_ave

In [22]:
import os

adj_save_filename = os.path.join(data_folder, 'adjusted_translated_positions_all.txt')
print(adj_save_filename)
np.savetxt(adj_save_filename, adjusted_new_positions, fmt='%.2f', delimiter=',')

D:\Shiwei\20210706-P_Forebrain_CTP09_only\adjusted_translated_positions_all.txt
